### ISSUE TITLE
GenOp.rot is the identity function

### ISSUE THREAD

**Issue by eddieschoute** [msr-quarc/ReVerC#2]
When testing some code using the `GenOp.rot` function
```
let constf = 
        let b: bool array = [|false; true|]
        b, GenOp.rot 1 b
```
both returned values are equal. The shift function is not applied here: https://github.com/msr-quarc/ReVerC/blob/master/src/GenOp.fst#L18, instead it seems to be a "stub" identity function.

## Expected behavior
I would expect `GenOp.rot 1` to shift the array by one, as it does when actually compiling to circuit code.

**Comment by meamy** [comment]
GenOp.rot should now perform the same rotation as the compiled circuit.
